export enum AppRoutes {
    Home = "/",
    Auth = "/auth",
    SignIn = "/auth/sign-in",
    SignUp = "/auth/sign-up",
    ResetPassword = "/auth/reset",
    RequestResetPassword = "/auth/request-reset",
    Profile = "/profile",
    Servises = "/services",
    Projects = "/projects",
    AdminProjects = "/admin/projects",
    Contact = "/contact",
    GetQuote = "/get-quote",
    Faq = "/faq",
    PrivacyPolicy = "/privacy-policy",
    Error = "/error",
    Error404 = "/error/404",
    ErrorSessionExpired = "/error/session-expired",
    ErrorConnectionError = "/error/connection-error",
    Administration = "/admin",
    About = "/about",
    AddEditProject = "/add-edit-project",
    Billing = "/billing",
}

export const RouteDefinitions = [
    { key: AppRoutes.Home, label: "Home", showInTopbar: true },
    { key: AppRoutes.Servises, label: "Services", showInTopbar: true },
    { key: AppRoutes.About, label: "About", showInTopbar: true },
    { key: AppRoutes.Projects, label: "Portfolio", showInTopbar: true },
    { key: AppRoutes.SignIn, label: "Sign In" },
    { key: AppRoutes.SignUp, label: "Sign Up" },
    { key: AppRoutes.ResetPassword, label: "Reset" },
    { key: AppRoutes.RequestResetPassword, label: "Request Reset Password" },
    { key: AppRoutes.Profile, label: "profile" },
    { key: AppRoutes.AdminProjects, label: "Admin Projects" },
    { key: AppRoutes.Billing, label: "Billing" },
    { key: AppRoutes.Faq, label: "faq" },
    { key: AppRoutes.PrivacyPolicy, label: "Privacy Policy" },
    { key: AppRoutes.Administration, label: "Administration" },
];